version: '3.8'

services:
  web:
    build:
      context: /SistemaBico.Web
      dockerfile: Dockerfile
    ports:
      - "5000:80"

  api:
    build:
      context: /SistemaBico.API
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - postgresql
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - RabbitConnection__HostName=rabbitmq
      - RabbitConnection__Port=5672
      - RabbitConnection__UserName=brttblack23
      - RabbitConnection__Password=@Leteelias5307
      - RabbitConnection__VirtualHost=cherry_broker
      - ConnectionStrings__DefaultConnection=Host=postgresql;Database=bico;Username=brttlback;Password=@Leteelias5307
    ports:
      - "5001:5001"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"

  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_USER: brttlback
      POSTGRES_PASSWORD: "@Leteelias5307"
      POSTGRES_DB: bico
    ports:
      - "5432:5432"