// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sistema.Bico.Infra.Context;

#nullable disable

namespace Sistema.Bico.Infra.Migrations
{
    [DbContext(typeof(ContextBase))]
    partial class ContextBaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Sistema.Bico.Domain.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bairro")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Complemento")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Logradouro")
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Update")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ZipCode")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("PK_TB_Address");

                    b.ToTable("TB_Address", (string)null);
                });

            modelBuilder.Entity("Sistema.Bico.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Cancellation")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CpfCnpj")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("Enable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsServiceProvider")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<byte[]>("PerfilPicture")
                        .HasColumnType("bytea");

                    b.Property<int>("TypePeople")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Update")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id")
                        .HasName("PK_TB_Client");

                    b.ToTable("TB_Client", (string)null);
                });

            modelBuilder.Entity("Sistema.Bico.Domain.Entities.ProfessionalArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Codigo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Update")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id")
                        .HasName("PK_TB_ProfessionalArea");

                    b.ToTable("TB_ProfessionalArea", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("53e872b0-fd3a-49c1-b47d-d03af76e11f9"),
                            Codigo = 1,
                            Created = new DateTime(2023, 3, 15, 13, 58, 1, 934, DateTimeKind.Local).AddTicks(7117),
                            Description = "Assistência Técnica"
                        },
                        new
                        {
                            Id = new Guid("27f1af35-f460-4104-b46c-7a4c04b2992e"),
                            Codigo = 2,
                            Created = new DateTime(2023, 3, 15, 13, 58, 1, 934, DateTimeKind.Local).AddTicks(7161),
                            Description = "Administação e Finanças"
                        },
                        new
                        {
                            Id = new Guid("f95de07a-ab29-44b5-9987-1b11c104cfaf"),
                            Codigo = 3,
                            Created = new DateTime(2023, 3, 15, 13, 58, 1, 934, DateTimeKind.Local).AddTicks(7164),
                            Description = "Veículos"
                        },
                        new
                        {
                            Id = new Guid("8f80f502-2dae-411f-89c8-c21fd1150591"),
                            Codigo = 4,
                            Created = new DateTime(2023, 3, 15, 13, 58, 1, 934, DateTimeKind.Local).AddTicks(7166),
                            Description = "Autos"
                        },
                        new
                        {
                            Id = new Guid("a9f3ab80-ca51-435a-8b12-23ebb2be1a70"),
                            Codigo = 5,
                            Created = new DateTime(2023, 3, 15, 13, 58, 1, 934, DateTimeKind.Local).AddTicks(7168),
                            Description = "Consultoria"
                        },
                        new
                        {
                            Id = new Guid("766a8025-d225-43e5-9d61-5b7e084f32df"),
                            Codigo = 6,
                            Created = new DateTime(2023, 3, 15, 13, 58, 1, 934, DateTimeKind.Local).AddTicks(7169),
                            Description = "Criador de Conteúdos"
                        },
                        new
                        {
                            Id = new Guid("4318304a-c7b6-41ce-8883-54784cf0f751"),
                            Codigo = 7,
                            Created = new DateTime(2023, 3, 15, 13, 58, 1, 934, DateTimeKind.Local).AddTicks(7170),
                            Description = "Comunicação"
                        },
                        new
                        {
                            Id = new Guid("260656e6-2295-4e8d-99d5-05e151cded13"),
                            Codigo = 8,
                            Created = new DateTime(2023, 3, 15, 13, 58, 1, 934, DateTimeKind.Local).AddTicks(7189),
                            Description = "Design/Tecnologia"
                        },
                        new
                        {
                            Id = new Guid("5e41ee15-6f50-4303-a541-a6b2f90ac202"),
                            Codigo = 9,
                            Created = new DateTime(2023, 3, 15, 13, 58, 1, 934, DateTimeKind.Local).AddTicks(7191),
                            Description = "Eventos"
                        },
                        new
                        {
                            Id = new Guid("d110d08a-a92e-4b1b-a3d7-bc25b2cb3955"),
                            Codigo = 10,
                            Created = new DateTime(2023, 3, 15, 13, 58, 1, 934, DateTimeKind.Local).AddTicks(7192),
                            Description = "Entregador"
                        },
                        new
                        {
                            Id = new Guid("279cd0f1-21d4-46c5-8eaa-ec681331ecec"),
                            Codigo = 11,
                            Created = new DateTime(2023, 3, 15, 13, 58, 1, 934, DateTimeKind.Local).AddTicks(7193),
                            Description = "Engenharias"
                        },
                        new
                        {
                            Id = new Guid("1a92ee06-2f5c-443b-954d-d21ba742c693"),
                            Codigo = 12,
                            Created = new DateTime(2023, 3, 15, 13, 58, 1, 934, DateTimeKind.Local).AddTicks(7195),
                            Description = "Edição de Vídeos"
                        },
                        new
                        {
                            Id = new Guid("b8171e9d-c777-4d39-bc3d-0d70ea845491"),
                            Codigo = 13,
                            Created = new DateTime(2023, 3, 15, 13, 58, 1, 934, DateTimeKind.Local).AddTicks(7196),
                            Description = "Tradução e Conteúdos"
                        },
                        new
                        {
                            Id = new Guid("ac7d28ca-0a2d-43fd-984c-ae48ac80de1b"),
                            Codigo = 14,
                            Created = new DateTime(2023, 3, 15, 13, 58, 1, 934, DateTimeKind.Local).AddTicks(7198),
                            Description = "Marketing e Vendas"
                        },
                        new
                        {
                            Id = new Guid("e23d54a7-6c6f-4506-8dea-a3a480bdc447"),
                            Codigo = 15,
                            Created = new DateTime(2023, 3, 15, 13, 58, 1, 934, DateTimeKind.Local).AddTicks(7199),
                            Description = "Moda e Beleza"
                        },
                        new
                        {
                            Id = new Guid("f5f77db0-9656-4e8d-bc41-e0149d3a7ec1"),
                            Codigo = 16,
                            Created = new DateTime(2023, 3, 15, 13, 58, 1, 934, DateTimeKind.Local).AddTicks(7203),
                            Description = "Jurídico"
                        },
                        new
                        {
                            Id = new Guid("8a0a311f-4ea0-4dc5-b298-1f8bd38663a0"),
                            Codigo = 17,
                            Created = new DateTime(2023, 3, 15, 13, 58, 1, 934, DateTimeKind.Local).AddTicks(7204),
                            Description = "Reformas e Reparos"
                        },
                        new
                        {
                            Id = new Guid("d0770626-8dfc-4ae9-a995-5da95f3dff5b"),
                            Codigo = 18,
                            Created = new DateTime(2023, 3, 15, 13, 58, 1, 934, DateTimeKind.Local).AddTicks(7206),
                            Description = "Saúde"
                        },
                        new
                        {
                            Id = new Guid("c34c845c-9593-403d-848e-a9ea6782a99e"),
                            Codigo = 19,
                            Created = new DateTime(2023, 3, 15, 13, 58, 1, 934, DateTimeKind.Local).AddTicks(7207),
                            Description = "Serviços Domésticos"
                        });
                });

            modelBuilder.Entity("Sistema.Bico.Domain.Entities.ProfessionalClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ProfessionalProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("StatusWorker")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Update")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id")
                        .HasName("PK_TB_ProfessionalClient");

                    b.HasIndex("ClientId");

                    b.HasIndex("ProfessionalProfileId");

                    b.ToTable("TB_ProfessionalClient", (string)null);
                });

            modelBuilder.Entity("Sistema.Bico.Domain.Entities.ProfessionalEspeciality", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("IdProfessionalProfile")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Update")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id")
                        .HasName("PK_TB_ProfessionalEspeciality");

                    b.HasIndex("IdProfessionalProfile");

                    b.ToTable("TB_ProfessionalEspeciality", (string)null);
                });

            modelBuilder.Entity("Sistema.Bico.Domain.Entities.ProfessionalPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Enable")
                        .HasColumnType("boolean");

                    b.Property<long?>("PagamentoId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid");

                    b.Property<int>("StatusPayment")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Update")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id")
                        .HasName("PK_TB_ProfessionalPayment");

                    b.HasIndex("ProfessionalId");

                    b.ToTable("TB_ProfessionalPayment", (string)null);
                });

            modelBuilder.Entity("Sistema.Bico.Domain.Entities.ProfessionalProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("About")
                        .HasColumnType("text");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Avaliation")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Perfil")
                        .HasColumnType("text");

                    b.Property<byte[]>("PerfilPicture")
                        .HasColumnType("bytea");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<bool>("Premium")
                        .HasColumnType("boolean");

                    b.Property<string>("Profession")
                        .HasColumnType("text");

                    b.Property<Guid?>("ProfessionalAreaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Update")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id")
                        .HasName("PK_TB_ProfessionalProfile");

                    b.HasIndex("AddressId");

                    b.HasIndex("ClientId");

                    b.HasIndex("ProfessionalAreaId");

                    b.ToTable("TB_ProfessionalProfile", (string)null);
                });

            modelBuilder.Entity("Sistema.Bico.Domain.Entities.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("TypeTemplate")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Update")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id")
                        .HasName("PK_TB_Template");

                    b.ToTable("TB_Template", (string)null);
                });

            modelBuilder.Entity("Sistema.Bico.Domain.Entities.TermUse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("TypeTerm")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Update")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PK_TB_TermUse");

                    b.ToTable("TB_TermUse", (string)null);
                });

            modelBuilder.Entity("Sistema.Bico.Domain.Entities.ThreeAvaliation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Communication")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Deadline")
                        .HasColumnType("numeric");

                    b.Property<int>("NumberAvaliation")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProfessionalProfileId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quality")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("Update")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id")
                        .HasName("PK_TB_ThreeAvaliation");

                    b.HasIndex("ProfessionalProfileId");

                    b.ToTable("TB_ThreeAvaliation", (string)null);
                });

            modelBuilder.Entity("Sistema.Bico.Domain.Entities.Worker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("About")
                        .HasColumnType("text");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsConcluded")
                        .HasColumnType("boolean");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<double?>("Price")
                        .HasColumnType("double precision");

                    b.Property<string>("Profession")
                        .HasColumnType("text");

                    b.Property<Guid?>("ProfessionalAreaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProfessionalProfileConcludedId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Update")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id")
                        .HasName("PK_TB_Worker");

                    b.HasIndex("AddressId");

                    b.HasIndex("ClientId");

                    b.HasIndex("ProfessionalAreaId");

                    b.HasIndex("ProfessionalProfileConcludedId");

                    b.ToTable("TB_Worker", (string)null);
                });

            modelBuilder.Entity("Sistema.Bico.Domain.Entities.WorkerDone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Avaliation")
                        .HasColumnType("numeric");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Update")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("WorkerDoneProfessionalId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK_TB_WorkerDone");

                    b.HasIndex("WorkerDoneProfessionalId");

                    b.ToTable("TB_WorkerDone", (string)null);
                });

            modelBuilder.Entity("Sistema.Bico.Domain.Entities.WorkerDoneProfessional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ProfessionalProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Update")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id")
                        .HasName("PK_TB_WorkerDoneProfessional");

                    b.HasIndex("ProfessionalProfileId");

                    b.ToTable("TB_WorkerDoneProfessional", (string)null);
                });

            modelBuilder.Entity("Sistema.Bico.Domain.Entities.WorkerProfessional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsConcluded")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ProfessionalProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Update")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("WorkerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK_TB_WorkerProfessional");

                    b.HasIndex("ProfessionalProfileId");

                    b.HasIndex("WorkerId");

                    b.ToTable("TB_WorkerProfessional", (string)null);
                });

            modelBuilder.Entity("Sistema.Bico.Domain.Generics.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id")
                        .HasName("PK_TB_AspNetUsers");

                    b.HasIndex("ClientId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Sistema.Bico.Domain.Generics.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Sistema.Bico.Domain.Generics.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistema.Bico.Domain.Generics.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Sistema.Bico.Domain.Generics.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sistema.Bico.Domain.Entities.ProfessionalClient", b =>
                {
                    b.HasOne("Sistema.Bico.Domain.Entities.Client", "Client")
                        .WithMany("ProfessionalClient")
                        .HasForeignKey("ClientId");

                    b.HasOne("Sistema.Bico.Domain.Entities.ProfessionalProfile", "ProfessionalProfile")
                        .WithMany("ProfessionalClient")
                        .HasForeignKey("ProfessionalProfileId");

                    b.Navigation("Client");

                    b.Navigation("ProfessionalProfile");
                });

            modelBuilder.Entity("Sistema.Bico.Domain.Entities.ProfessionalEspeciality", b =>
                {
                    b.HasOne("Sistema.Bico.Domain.Entities.ProfessionalProfile", "ProfessionalProfile")
                        .WithMany("Especiality")
                        .HasForeignKey("IdProfessionalProfile")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProfessionalProfile");
                });

            modelBuilder.Entity("Sistema.Bico.Domain.Entities.ProfessionalPayment", b =>
                {
                    b.HasOne("Sistema.Bico.Domain.Entities.ProfessionalProfile", "Professional")
                        .WithMany()
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professional");
                });

            modelBuilder.Entity("Sistema.Bico.Domain.Entities.ProfessionalProfile", b =>
                {
                    b.HasOne("Sistema.Bico.Domain.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("Sistema.Bico.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistema.Bico.Domain.Entities.ProfessionalArea", "ProfessionalArea")
                        .WithMany()
                        .HasForeignKey("ProfessionalAreaId");

                    b.Navigation("Address");

                    b.Navigation("Client");

                    b.Navigation("ProfessionalArea");
                });

            modelBuilder.Entity("Sistema.Bico.Domain.Entities.ThreeAvaliation", b =>
                {
                    b.HasOne("Sistema.Bico.Domain.Entities.ProfessionalProfile", "ProfessionalProfile")
                        .WithMany()
                        .HasForeignKey("ProfessionalProfileId");

                    b.Navigation("ProfessionalProfile");
                });

            modelBuilder.Entity("Sistema.Bico.Domain.Entities.Worker", b =>
                {
                    b.HasOne("Sistema.Bico.Domain.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("Sistema.Bico.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistema.Bico.Domain.Entities.ProfessionalArea", "ProfessionalArea")
                        .WithMany()
                        .HasForeignKey("ProfessionalAreaId");

                    b.HasOne("Sistema.Bico.Domain.Entities.ProfessionalProfile", "ProfessionalProfileConcluded")
                        .WithMany()
                        .HasForeignKey("ProfessionalProfileConcludedId");

                    b.Navigation("Address");

                    b.Navigation("Client");

                    b.Navigation("ProfessionalArea");

                    b.Navigation("ProfessionalProfileConcluded");
                });

            modelBuilder.Entity("Sistema.Bico.Domain.Entities.WorkerDone", b =>
                {
                    b.HasOne("Sistema.Bico.Domain.Entities.WorkerDoneProfessional", "WorkerDoneProfessional")
                        .WithMany("WorkerDone")
                        .HasForeignKey("WorkerDoneProfessionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkerDoneProfessional");
                });

            modelBuilder.Entity("Sistema.Bico.Domain.Entities.WorkerDoneProfessional", b =>
                {
                    b.HasOne("Sistema.Bico.Domain.Entities.ProfessionalProfile", "ProfessionalProfile")
                        .WithMany("WorkerDoneProfessional")
                        .HasForeignKey("ProfessionalProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProfessionalProfile");
                });

            modelBuilder.Entity("Sistema.Bico.Domain.Entities.WorkerProfessional", b =>
                {
                    b.HasOne("Sistema.Bico.Domain.Entities.ProfessionalProfile", "ProfessionalProfile")
                        .WithMany("WorkerProfessional")
                        .HasForeignKey("ProfessionalProfileId");

                    b.HasOne("Sistema.Bico.Domain.Entities.Worker", "Worker")
                        .WithMany("WorkerProfessional")
                        .HasForeignKey("WorkerId");

                    b.Navigation("ProfessionalProfile");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("Sistema.Bico.Domain.Generics.Entities.ApplicationUser", b =>
                {
                    b.HasOne("Sistema.Bico.Domain.Entities.Client", "Client")
                        .WithMany("ApplicationUser")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Sistema.Bico.Domain.Entities.Client", b =>
                {
                    b.Navigation("ApplicationUser");

                    b.Navigation("ProfessionalClient");
                });

            modelBuilder.Entity("Sistema.Bico.Domain.Entities.ProfessionalProfile", b =>
                {
                    b.Navigation("Especiality");

                    b.Navigation("ProfessionalClient");

                    b.Navigation("WorkerDoneProfessional");

                    b.Navigation("WorkerProfessional");
                });

            modelBuilder.Entity("Sistema.Bico.Domain.Entities.Worker", b =>
                {
                    b.Navigation("WorkerProfessional");
                });

            modelBuilder.Entity("Sistema.Bico.Domain.Entities.WorkerDoneProfessional", b =>
                {
                    b.Navigation("WorkerDone");
                });
#pragma warning restore 612, 618
        }
    }
}
